FROM jh4mit/nojava-ipmi-kvm:v0.9.2-openjdk-7
ENV JAVA_VERSION=7u51
CMD ["-k", "-d", "Java/jviewer.jnlp", \
     "-u", "ADMIN", "-l", "rpc/WEBSES/create.asp", \
     "-U", "WEBVAR_USERNAME", "-P", "WEBVAR_PASSWORD", \
     "-K", "SessionCookie"]

